### ISSUE TITLE
ytmusicapi只有图片和歌词能加载出来，音乐后台显示302重定向后，报错404

### ISSUE THREAD

**Issue by Aqr-K** [xizeyoupan/ytmusic-api-server#1]
Meting是部署在本地的linux主机上的
ytmusicapi是部署在replit上的，因为没有root权限，所有用proot虚拟了一个有root的debian11
nodejs版本18.17.0
python版本3.9.2
ffmpeg版本是5.1.3
pip安装的每个组件版本号完全与docker版相同
源码使用的是1.2.1版本
因为replit自带了反代功能，所以没有用caddy

用replit搭建个梯子后直连，直接浏览器是能访问youtube和spotify的，也就是说IP段是可以看国外的，也能正常播放，直接访问`python -m yt_dlp --get-url -f ba https://youtube.com/watch?v=wr-6wwt8RXk`命令执行后的返回的网页，也是可以打开的。
就是/proxy出问题了

请教一下是什么原因呢？

 <-- GET /api?server=ytmusic&type=url&id=wr-6wwt8RXk
python -m yt_dlp --get-url -f ba https://youtube.com/watch?v=wr-6wwt8RXk
https://rr3---sn-qxoedne7.googlevideo.com/videoplayback?expire=1690732545&ei=oTPGZJWdK4W_lu8P7uCPkAM&ip=34.68.234.243&id=o-AOwiLRhmAUF6BvRM8rRJm3yhxXSo5ArhhICB35CIUFLl&itag=251&source=youtube&requiressl=yes&mh=E-&mm=31%2C26&mn=sn-qxoedne7%2Csn-5goeen7y&ms=au%2Conr&mv=m&mvi=3&pl=20&spc=Ul2Sq30-s3cHXfKQRmAJuoZK36vdluA&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4361444&dur=277.141&lmt=1540216187956787&mt=1690710095&fvip=2&keepalive=yes&fexp=24007246%2C24363392%2C51000014&beids=24350017&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIr_EI5rbDsdU16U_MSfIVp_0UQBxbMj94wdGG8Hzv-hAiAK2Vpt4GkJQf5d4vCdo2eVHMzvYWlXViNn92I_Ai-mhw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIgLprVphonoCnzh2WoEB2aJK-XtTusfrs9yt5TmgWYNVcCIQCQugBG-8w98qxPLIwWg914r0OtSki29sm6EuIN7D1OYQ%3D%3D

  --> GET /api?server=ytmusic&type=url&id=wr-6wwt8RXk 302 2,879ms 2.14kb
  <-- GET /proxy?expire=1690732545&ei=oTPGZJWdK4W_lu8P7uCPkAM&ip=34.68.234.243&id=o-AOwiLRhmAUF6BvRM8rRJm3yhxXSo5ArhhICB35CIUFLl&itag=251&source=youtube&requiressl=yes&mh=E-&mm=31%2C26&mn=sn-qxoedne7%2Csn-5goeen7y&ms=au%2Conr&mv=m&mvi=3&pl=20&spc=Ul2Sq30-s3cHXfKQRmAJuoZK36vdluA&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4361444&dur=277.141&lmt=1540216187956787&mt=1690710095&fvip=2&keepalive=yes&fexp=24007246%2C24363392%2C51000014&beids=24350017&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIr_EI5rbDsdU16U_MSfIVp_0UQBxbMj94wdGG8Hzv-hAiAK2Vpt4GkJQf5d4vCdo2eVHMzvYWlXViNn92I_Ai-mhw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIgLprVphonoCnzh2WoEB2aJK-XtTusfrs9yt5TmgWYNVcCIQCQugBG-8w98qxPLIwWg914r0OtSki29sm6EuIN7D1OYQ%3D%3D&self_upstream=rr3---sn-qxoedne7.googlevideo.com:443&self_path=/videoplayback
  --> GET /proxy?expire=1690732545&ei=oTPGZJWdK4W_lu8P7uCPkAM&ip=34.68.234.243&id=o-AOwiLRhmAUF6BvRM8rRJm3yhxXSo5ArhhICB35CIUFLl&itag=251&source=youtube&requiressl=yes&mh=E-&mm=31%2C26&mn=sn-qxoedne7%2Csn-5goeen7y&ms=au%2Conr&mv=m&mvi=3&pl=20&spc=Ul2Sq30-s3cHXfKQRmAJuoZK36vdluA&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4361444&dur=277.141&lmt=1540216187956787&mt=1690710095&fvip=2&keepalive=yes&fexp=24007246%2C24363392%2C51000014&beids=24350017&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIr_EI5rbDsdU16U_MSfIVp_0UQBxbMj94wdGG8Hzv-hAiAK2Vpt4GkJQf5d4vCdo2eVHMzvYWlXViNn92I_Ai-mhw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIgLprVphonoCnzh2WoEB2aJK-XtTusfrs9yt5TmgWYNVcCIQCQugBG-8w98qxPLIwWg914r0OtSki29sm6EuIN7D1OYQ%3D%3D&self_upstream=rr3---sn-qxoedne7.googlevideo.com:443&self_path=/videoplayback 404 1ms -

**Comment by xizeyoupan** [comment]
在原项目中/proxy路径的反代是通过caddy处理的，而不通过后端服务器，这是由于性能考虑。如需自行处理，比如上面的请求
```
/proxy?expire=1690732545&ei=oTPGZJWdK4W_lu8P7uCPkAM&ip=34.68.234.243&id=o-AOwiLRhmAUF6BvRM8rRJm3yhxXSo5ArhhICB35CIUFLl&itag=251&source=youtube&requiressl=yes&mh=E-&mm=31%2C26&mn=sn-qxoedne7%2Csn-5goeen7y&ms=au%2Conr&mv=m&mvi=3&pl=20&spc=Ul2Sq30-s3cHXfKQRmAJuoZK36vdluA&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4361444&dur=277.141&lmt=1540216187956787&mt=1690710095&fvip=2&keepalive=yes&fexp=24007246%2C24363392%2C51000014&beids=24350017&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIr_EI5rbDsdU16U_MSfIVp_0UQBxbMj94wdGG8Hzv-hAiAK2Vpt4GkJQf5d4vCdo2eVHMzvYWlXViNn92I_Ai-mhw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIgLprVphonoCnzh2WoEB2aJK-XtTusfrs9yt5TmgWYNVcCIQCQugBG-8w98qxPLIwWg914r0OtSki29sm6EuIN7D1OYQ%3D%3D&self_upstream=rr3---sn-qxoedne7.googlevideo.com:443&self_path=/videoplayback
```
为url，需保证实际上url转发到
```
https://rr3---sn-qxoedne7.googlevideo.com:443/videoplayback?expire=1690732545&ei=oTPGZJWdK4W_lu8P7uCPkAM&ip=34.68.234.243&id=o-AOwiLRhmAUF6BvRM8rRJm3yhxXSo5ArhhICB35CIUFLl&itag=251&source=youtube&requiressl=yes&mh=E-&mm=31%2C26&mn=sn-qxoedne7%2Csn-5goeen7y&ms=au%2Conr&mv=m&mvi=3&pl=20&spc=Ul2Sq30-s3cHXfKQRmAJuoZK36vdluA&vprv=1&svpuc=1&mime=audio%2Fwebm&gir=yes&clen=4361444&dur=277.141&lmt=1540216187956787&mt=1690710095&fvip=2&keepalive=yes&fexp=24007246%2C24363392%2C51000014&beids=24350017&c=ANDROID&txp=5511222&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cspc%2Cvprv%2Csvpuc%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=AOq0QJ8wRQIhAIr_EI5rbDsdU16U_MSfIVp_0UQBxbMj94wdGG8Hzv-hAiAK2Vpt4GkJQf5d4vCdo2eVHMzvYWlXViNn92I_Ai-mhw%3D%3D&lsparams=mh%2Cmm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl&lsig=AG3C_xAwRQIgLprVphonoCnzh2WoEB2aJK-XtTusfrs9yt5TmgWYNVcCIQCQugBG-8w98qxPLIwWg914r0OtSki29sm6EuIN7D1OYQ%3D%3D&self_upstream=rr3---sn-qxoedne7.googlevideo.com:443&self_path=/videoplayback
```
即域名为原url中最后的的self_upstream参数，路径为原url中的self_path参数，请求参数全部复制原来的即可

**Comment by Aqr-K** [comment]
replit里虚拟出来的debian11，在使用caddy的时候好像会出现莫名其妙的bug，但是nginx却不会
请教一下如果使用nginx该如何写nginx.conf配置啊？试着写了几版的rewrite都失败了

**Comment by xizeyoupan** [comment]
```
        location /proxy {
            proxy_pass https://$arg_self_upstream$arg_self_path?$args;
            proxy_set_header Host $arg_self_upstream;

            resolver 8.8.8.8;
        }
```
